#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA_MATRICULA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_matricula")]
	public partial class matriculaLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void Insertalumno(alumno instance);
    partial void Updatealumno(alumno instance);
    partial void Deletealumno(alumno instance);
    partial void Insertcarrera_profesional(carrera_profesional instance);
    partial void Updatecarrera_profesional(carrera_profesional instance);
    partial void Deletecarrera_profesional(carrera_profesional instance);
    partial void Insertcursos(cursos instance);
    partial void Updatecursos(cursos instance);
    partial void Deletecursos(cursos instance);
    partial void Insertdetalle_matricula(detalle_matricula instance);
    partial void Updatedetalle_matricula(detalle_matricula instance);
    partial void Deletedetalle_matricula(detalle_matricula instance);
    partial void Insertmatricula(matricula instance);
    partial void Updatematricula(matricula instance);
    partial void Deletematricula(matricula instance);
    #endregion
		
		public matriculaLINQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bd_matriculaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public matriculaLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public matriculaLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public matriculaLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public matriculaLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<alumno> alumno
		{
			get
			{
				return this.GetTable<alumno>();
			}
		}
		
		public System.Data.Linq.Table<carrera_profesional> carrera_profesional
		{
			get
			{
				return this.GetTable<carrera_profesional>();
			}
		}
		
		public System.Data.Linq.Table<cursos> cursos
		{
			get
			{
				return this.GetTable<cursos>();
			}
		}
		
		public System.Data.Linq.Table<detalle_matricula> detalle_matricula
		{
			get
			{
				return this.GetTable<detalle_matricula>();
			}
		}
		
		public System.Data.Linq.Table<matricula> matricula
		{
			get
			{
				return this.GetTable<matricula>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN")]
		public ISingleResult<SP_LOGINResult> SP_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_LOGIN", DbType="NVarChar(50)")] string uSER_LOGIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PASSWORD", DbType="NVarChar(1000)")] string uSER_PASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_LOGIN, uSER_PASSWORD);
			return ((ISingleResult<SP_LOGINResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_NUEVO_CURSO")]
		public int SP_NUEVO_CURSO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string nombrecurso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idecarrera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> semestrecur, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombrecurso, idecarrera, semestrecur, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EDTAR_CURSO")]
		public int SP_EDTAR_CURSO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ide, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idecar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> semes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string desc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ide, nom, idecar, semes, desc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_NUEVO_ALUMNO")]
		public int SP_NUEVO_ALUMNO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string apepaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string apematerno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string dni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechnac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string tel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idcar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apepaterno, apematerno, nombre, sex, dni, fechnac, email, tel, idcar);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EDITAR_ALUMNO")]
		public int SP_EDITAR_ALUMNO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string apepaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string apematerno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string dni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechnac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string tel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idcar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idealu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apepaterno, apematerno, nombre, sex, dni, fechnac, email, tel, idcar, idealu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTA_CURSO_CARRERA")]
		public ISingleResult<SP_LISTA_CURSO_CARRERAResult> SP_LISTA_CURSO_CARRERA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idecar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idsem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idecar, idsem);
			return ((ISingleResult<SP_LISTA_CURSO_CARRERAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_NUEVA_MATRICULA")]
		public ISingleResult<SP_NUEVA_MATRICULAResult> SP_NUEVA_MATRICULA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idalumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> semestre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string codigo_pago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, idalumno, semestre, codigo_pago);
			return ((ISingleResult<SP_NUEVA_MATRICULAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MATRICULAR_CURSO")]
		public int SP_MATRICULAR_CURSO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idemat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idecur)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idemat, idecur);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTA_MATRICULA")]
		public ISingleResult<SP_LISTA_MATRICULAResult> SP_LISTA_MATRICULA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idecar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fech_inicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fech_fin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idecar, fech_inicio, fech_fin);
			return ((ISingleResult<SP_LISTA_MATRICULAResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _login;
		
		private string _clave;
		
		private string _tipo;
		
		private System.Nullable<char> _estado;
		
		private EntitySet<matricula> _matricula;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OnestadoChanging(System.Nullable<char> value);
    partial void OnestadoChanged();
    #endregion
		
		public usuario()
		{
			this._matricula = new EntitySet<matricula>(new Action<matricula>(this.attach_matricula), new Action<matricula>(this.detach_matricula));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Char(3)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1)")]
		public System.Nullable<char> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_matricula", Storage="_matricula", ThisKey="login", OtherKey="login")]
		public EntitySet<matricula> matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				this._matricula.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_matricula(matricula entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_matricula(matricula entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumno")]
	public partial class alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idalumno;
		
		private string _apellido_paterno;
		
		private string _apellido_materno;
		
		private string _nombres;
		
		private System.Nullable<char> _sexo;
		
		private string _dni;
		
		private System.DateTime _fecha_nacimiento;
		
		private string _email;
		
		private string _telefono;
		
		private int _idcarrera;
		
		private EntitySet<matricula> _matricula;
		
		private EntityRef<carrera_profesional> _carrera_profesional;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidalumnoChanging(int value);
    partial void OnidalumnoChanged();
    partial void Onapellido_paternoChanging(string value);
    partial void Onapellido_paternoChanged();
    partial void Onapellido_maternoChanging(string value);
    partial void Onapellido_maternoChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnsexoChanging(System.Nullable<char> value);
    partial void OnsexoChanged();
    partial void OndniChanging(string value);
    partial void OndniChanged();
    partial void Onfecha_nacimientoChanging(System.DateTime value);
    partial void Onfecha_nacimientoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnidcarreraChanging(int value);
    partial void OnidcarreraChanged();
    #endregion
		
		public alumno()
		{
			this._matricula = new EntitySet<matricula>(new Action<matricula>(this.attach_matricula), new Action<matricula>(this.detach_matricula));
			this._carrera_profesional = default(EntityRef<carrera_profesional>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idalumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idalumno
		{
			get
			{
				return this._idalumno;
			}
			set
			{
				if ((this._idalumno != value))
				{
					this.OnidalumnoChanging(value);
					this.SendPropertyChanging();
					this._idalumno = value;
					this.SendPropertyChanged("idalumno");
					this.OnidalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_paterno", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string apellido_paterno
		{
			get
			{
				return this._apellido_paterno;
			}
			set
			{
				if ((this._apellido_paterno != value))
				{
					this.Onapellido_paternoChanging(value);
					this.SendPropertyChanging();
					this._apellido_paterno = value;
					this.SendPropertyChanged("apellido_paterno");
					this.Onapellido_paternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_materno", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string apellido_materno
		{
			get
			{
				return this._apellido_materno;
			}
			set
			{
				if ((this._apellido_materno != value))
				{
					this.Onapellido_maternoChanging(value);
					this.SendPropertyChanging();
					this._apellido_materno = value;
					this.SendPropertyChanged("apellido_materno");
					this.Onapellido_maternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1)")]
		public System.Nullable<char> sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date NOT NULL")]
		public System.DateTime fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(45)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(45)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcarrera", DbType="Int NOT NULL")]
		public int idcarrera
		{
			get
			{
				return this._idcarrera;
			}
			set
			{
				if ((this._idcarrera != value))
				{
					if (this._carrera_profesional.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidcarreraChanging(value);
					this.SendPropertyChanging();
					this._idcarrera = value;
					this.SendPropertyChanged("idcarrera");
					this.OnidcarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_matricula", Storage="_matricula", ThisKey="idalumno", OtherKey="idalumno")]
		public EntitySet<matricula> matricula
		{
			get
			{
				return this._matricula;
			}
			set
			{
				this._matricula.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_profesional_alumno", Storage="_carrera_profesional", ThisKey="idcarrera", OtherKey="idcarrera", IsForeignKey=true)]
		public carrera_profesional carrera_profesional
		{
			get
			{
				return this._carrera_profesional.Entity;
			}
			set
			{
				carrera_profesional previousValue = this._carrera_profesional.Entity;
				if (((previousValue != value) 
							|| (this._carrera_profesional.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrera_profesional.Entity = null;
						previousValue.alumno.Remove(this);
					}
					this._carrera_profesional.Entity = value;
					if ((value != null))
					{
						value.alumno.Add(this);
						this._idcarrera = value.idcarrera;
					}
					else
					{
						this._idcarrera = default(int);
					}
					this.SendPropertyChanged("carrera_profesional");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_matricula(matricula entity)
		{
			this.SendPropertyChanging();
			entity.alumno = this;
		}
		
		private void detach_matricula(matricula entity)
		{
			this.SendPropertyChanging();
			entity.alumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrera_profesional")]
	public partial class carrera_profesional : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcarrera;
		
		private string _nombre_carrera;
		
		private char _estado;
		
		private EntitySet<alumno> _alumno;
		
		private EntitySet<cursos> _cursos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcarreraChanging(int value);
    partial void OnidcarreraChanged();
    partial void Onnombre_carreraChanging(string value);
    partial void Onnombre_carreraChanged();
    partial void OnestadoChanging(char value);
    partial void OnestadoChanged();
    #endregion
		
		public carrera_profesional()
		{
			this._alumno = new EntitySet<alumno>(new Action<alumno>(this.attach_alumno), new Action<alumno>(this.detach_alumno));
			this._cursos = new EntitySet<cursos>(new Action<cursos>(this.attach_cursos), new Action<cursos>(this.detach_cursos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcarrera", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idcarrera
		{
			get
			{
				return this._idcarrera;
			}
			set
			{
				if ((this._idcarrera != value))
				{
					this.OnidcarreraChanging(value);
					this.SendPropertyChanging();
					this._idcarrera = value;
					this.SendPropertyChanged("idcarrera");
					this.OnidcarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_carrera", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_carrera
		{
			get
			{
				return this._nombre_carrera;
			}
			set
			{
				if ((this._nombre_carrera != value))
				{
					this.Onnombre_carreraChanging(value);
					this.SendPropertyChanging();
					this._nombre_carrera = value;
					this.SendPropertyChanged("nombre_carrera");
					this.Onnombre_carreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1) NOT NULL")]
		public char estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_profesional_alumno", Storage="_alumno", ThisKey="idcarrera", OtherKey="idcarrera")]
		public EntitySet<alumno> alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				this._alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_profesional_cursos", Storage="_cursos", ThisKey="idcarrera", OtherKey="idcarrera")]
		public EntitySet<cursos> cursos
		{
			get
			{
				return this._cursos;
			}
			set
			{
				this._cursos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_alumno(alumno entity)
		{
			this.SendPropertyChanging();
			entity.carrera_profesional = this;
		}
		
		private void detach_alumno(alumno entity)
		{
			this.SendPropertyChanging();
			entity.carrera_profesional = null;
		}
		
		private void attach_cursos(cursos entity)
		{
			this.SendPropertyChanging();
			entity.carrera_profesional = this;
		}
		
		private void detach_cursos(cursos entity)
		{
			this.SendPropertyChanging();
			entity.carrera_profesional = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cursos")]
	public partial class cursos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcursos;
		
		private string _nombre;
		
		private int _idcarrera;
		
		private int _semestre;
		
		private string _obs;
		
		private EntitySet<detalle_matricula> _detalle_matricula;
		
		private EntityRef<carrera_profesional> _carrera_profesional;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcursosChanging(int value);
    partial void OnidcursosChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnidcarreraChanging(int value);
    partial void OnidcarreraChanged();
    partial void OnsemestreChanging(int value);
    partial void OnsemestreChanged();
    partial void OnobsChanging(string value);
    partial void OnobsChanged();
    #endregion
		
		public cursos()
		{
			this._detalle_matricula = new EntitySet<detalle_matricula>(new Action<detalle_matricula>(this.attach_detalle_matricula), new Action<detalle_matricula>(this.detach_detalle_matricula));
			this._carrera_profesional = default(EntityRef<carrera_profesional>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcursos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idcursos
		{
			get
			{
				return this._idcursos;
			}
			set
			{
				if ((this._idcursos != value))
				{
					this.OnidcursosChanging(value);
					this.SendPropertyChanging();
					this._idcursos = value;
					this.SendPropertyChanged("idcursos");
					this.OnidcursosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcarrera", DbType="Int NOT NULL")]
		public int idcarrera
		{
			get
			{
				return this._idcarrera;
			}
			set
			{
				if ((this._idcarrera != value))
				{
					if (this._carrera_profesional.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidcarreraChanging(value);
					this.SendPropertyChanging();
					this._idcarrera = value;
					this.SendPropertyChanged("idcarrera");
					this.OnidcarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semestre", DbType="Int NOT NULL")]
		public int semestre
		{
			get
			{
				return this._semestre;
			}
			set
			{
				if ((this._semestre != value))
				{
					this.OnsemestreChanging(value);
					this.SendPropertyChanging();
					this._semestre = value;
					this.SendPropertyChanged("semestre");
					this.OnsemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs", DbType="VarChar(45)")]
		public string obs
		{
			get
			{
				return this._obs;
			}
			set
			{
				if ((this._obs != value))
				{
					this.OnobsChanging(value);
					this.SendPropertyChanging();
					this._obs = value;
					this.SendPropertyChanged("obs");
					this.OnobsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cursos_detalle_matricula", Storage="_detalle_matricula", ThisKey="idcursos", OtherKey="idcursos")]
		public EntitySet<detalle_matricula> detalle_matricula
		{
			get
			{
				return this._detalle_matricula;
			}
			set
			{
				this._detalle_matricula.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrera_profesional_cursos", Storage="_carrera_profesional", ThisKey="idcarrera", OtherKey="idcarrera", IsForeignKey=true)]
		public carrera_profesional carrera_profesional
		{
			get
			{
				return this._carrera_profesional.Entity;
			}
			set
			{
				carrera_profesional previousValue = this._carrera_profesional.Entity;
				if (((previousValue != value) 
							|| (this._carrera_profesional.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrera_profesional.Entity = null;
						previousValue.cursos.Remove(this);
					}
					this._carrera_profesional.Entity = value;
					if ((value != null))
					{
						value.cursos.Add(this);
						this._idcarrera = value.idcarrera;
					}
					else
					{
						this._idcarrera = default(int);
					}
					this.SendPropertyChanged("carrera_profesional");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_matricula(detalle_matricula entity)
		{
			this.SendPropertyChanging();
			entity.cursos = this;
		}
		
		private void detach_detalle_matricula(detalle_matricula entity)
		{
			this.SendPropertyChanging();
			entity.cursos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_matricula")]
	public partial class detalle_matricula : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iddetalle_matricula;
		
		private int _idmatricula;
		
		private int _idcursos;
		
		private EntityRef<cursos> _cursos;
		
		private EntityRef<matricula> _matricula;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oniddetalle_matriculaChanging(int value);
    partial void Oniddetalle_matriculaChanged();
    partial void OnidmatriculaChanging(int value);
    partial void OnidmatriculaChanged();
    partial void OnidcursosChanging(int value);
    partial void OnidcursosChanged();
    #endregion
		
		public detalle_matricula()
		{
			this._cursos = default(EntityRef<cursos>);
			this._matricula = default(EntityRef<matricula>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddetalle_matricula", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iddetalle_matricula
		{
			get
			{
				return this._iddetalle_matricula;
			}
			set
			{
				if ((this._iddetalle_matricula != value))
				{
					this.Oniddetalle_matriculaChanging(value);
					this.SendPropertyChanging();
					this._iddetalle_matricula = value;
					this.SendPropertyChanged("iddetalle_matricula");
					this.Oniddetalle_matriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmatricula", DbType="Int NOT NULL")]
		public int idmatricula
		{
			get
			{
				return this._idmatricula;
			}
			set
			{
				if ((this._idmatricula != value))
				{
					if (this._matricula.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidmatriculaChanging(value);
					this.SendPropertyChanging();
					this._idmatricula = value;
					this.SendPropertyChanged("idmatricula");
					this.OnidmatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcursos", DbType="Int NOT NULL")]
		public int idcursos
		{
			get
			{
				return this._idcursos;
			}
			set
			{
				if ((this._idcursos != value))
				{
					if (this._cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidcursosChanging(value);
					this.SendPropertyChanging();
					this._idcursos = value;
					this.SendPropertyChanged("idcursos");
					this.OnidcursosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cursos_detalle_matricula", Storage="_cursos", ThisKey="idcursos", OtherKey="idcursos", IsForeignKey=true)]
		public cursos cursos
		{
			get
			{
				return this._cursos.Entity;
			}
			set
			{
				cursos previousValue = this._cursos.Entity;
				if (((previousValue != value) 
							|| (this._cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cursos.Entity = null;
						previousValue.detalle_matricula.Remove(this);
					}
					this._cursos.Entity = value;
					if ((value != null))
					{
						value.detalle_matricula.Add(this);
						this._idcursos = value.idcursos;
					}
					else
					{
						this._idcursos = default(int);
					}
					this.SendPropertyChanged("cursos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="matricula_detalle_matricula", Storage="_matricula", ThisKey="idmatricula", OtherKey="idmatricula", IsForeignKey=true)]
		public matricula matricula
		{
			get
			{
				return this._matricula.Entity;
			}
			set
			{
				matricula previousValue = this._matricula.Entity;
				if (((previousValue != value) 
							|| (this._matricula.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._matricula.Entity = null;
						previousValue.detalle_matricula.Remove(this);
					}
					this._matricula.Entity = value;
					if ((value != null))
					{
						value.detalle_matricula.Add(this);
						this._idmatricula = value.idmatricula;
					}
					else
					{
						this._idmatricula = default(int);
					}
					this.SendPropertyChanged("matricula");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.matricula")]
	public partial class matricula : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idmatricula;
		
		private string _login;
		
		private int _idalumno;
		
		private System.Nullable<int> _semestre;
		
		private string _codigo_pago;
		
		private System.DateTime _fecha_matricula;
		
		private char _estado;
		
		private EntitySet<detalle_matricula> _detalle_matricula;
		
		private EntityRef<alumno> _alumno;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidmatriculaChanging(int value);
    partial void OnidmatriculaChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnidalumnoChanging(int value);
    partial void OnidalumnoChanged();
    partial void OnsemestreChanging(System.Nullable<int> value);
    partial void OnsemestreChanged();
    partial void Oncodigo_pagoChanging(string value);
    partial void Oncodigo_pagoChanged();
    partial void Onfecha_matriculaChanging(System.DateTime value);
    partial void Onfecha_matriculaChanged();
    partial void OnestadoChanging(char value);
    partial void OnestadoChanged();
    #endregion
		
		public matricula()
		{
			this._detalle_matricula = new EntitySet<detalle_matricula>(new Action<detalle_matricula>(this.attach_detalle_matricula), new Action<detalle_matricula>(this.detach_detalle_matricula));
			this._alumno = default(EntityRef<alumno>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmatricula", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idmatricula
		{
			get
			{
				return this._idmatricula;
			}
			set
			{
				if ((this._idmatricula != value))
				{
					this.OnidmatriculaChanging(value);
					this.SendPropertyChanging();
					this._idmatricula = value;
					this.SendPropertyChanged("idmatricula");
					this.OnidmatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idalumno", DbType="Int NOT NULL")]
		public int idalumno
		{
			get
			{
				return this._idalumno;
			}
			set
			{
				if ((this._idalumno != value))
				{
					if (this._alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidalumnoChanging(value);
					this.SendPropertyChanging();
					this._idalumno = value;
					this.SendPropertyChanged("idalumno");
					this.OnidalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semestre", DbType="Int")]
		public System.Nullable<int> semestre
		{
			get
			{
				return this._semestre;
			}
			set
			{
				if ((this._semestre != value))
				{
					this.OnsemestreChanging(value);
					this.SendPropertyChanging();
					this._semestre = value;
					this.SendPropertyChanged("semestre");
					this.OnsemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_pago", DbType="VarChar(45)")]
		public string codigo_pago
		{
			get
			{
				return this._codigo_pago;
			}
			set
			{
				if ((this._codigo_pago != value))
				{
					this.Oncodigo_pagoChanging(value);
					this.SendPropertyChanging();
					this._codigo_pago = value;
					this.SendPropertyChanged("codigo_pago");
					this.Oncodigo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_matricula", DbType="DateTime2 NOT NULL")]
		public System.DateTime fecha_matricula
		{
			get
			{
				return this._fecha_matricula;
			}
			set
			{
				if ((this._fecha_matricula != value))
				{
					this.Onfecha_matriculaChanging(value);
					this.SendPropertyChanging();
					this._fecha_matricula = value;
					this.SendPropertyChanged("fecha_matricula");
					this.Onfecha_matriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1) NOT NULL")]
		public char estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="matricula_detalle_matricula", Storage="_detalle_matricula", ThisKey="idmatricula", OtherKey="idmatricula")]
		public EntitySet<detalle_matricula> detalle_matricula
		{
			get
			{
				return this._detalle_matricula;
			}
			set
			{
				this._detalle_matricula.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_matricula", Storage="_alumno", ThisKey="idalumno", OtherKey="idalumno", IsForeignKey=true)]
		public alumno alumno
		{
			get
			{
				return this._alumno.Entity;
			}
			set
			{
				alumno previousValue = this._alumno.Entity;
				if (((previousValue != value) 
							|| (this._alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._alumno.Entity = null;
						previousValue.matricula.Remove(this);
					}
					this._alumno.Entity = value;
					if ((value != null))
					{
						value.matricula.Add(this);
						this._idalumno = value.idalumno;
					}
					else
					{
						this._idalumno = default(int);
					}
					this.SendPropertyChanged("alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_matricula", Storage="_usuario", ThisKey="login", OtherKey="login", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.matricula.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.matricula.Add(this);
						this._login = value.login;
					}
					else
					{
						this._login = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_matricula(detalle_matricula entity)
		{
			this.SendPropertyChanging();
			entity.matricula = this;
		}
		
		private void detach_detalle_matricula(detalle_matricula entity)
		{
			this.SendPropertyChanging();
			entity.matricula = null;
		}
	}
	
	public partial class SP_LOGINResult
	{
		
		private string _login;
		
		private string _tipo;
		
		public SP_LOGINResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this._login = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Char(3)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
	}
	
	public partial class SP_LISTA_CURSO_CARRERAResult
	{
		
		private int _idcursos;
		
		private string _nombre;
		
		private int _idcarrera;
		
		private int _semestre;
		
		private string _obs;
		
		public SP_LISTA_CURSO_CARRERAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcursos", DbType="Int NOT NULL")]
		public int idcursos
		{
			get
			{
				return this._idcursos;
			}
			set
			{
				if ((this._idcursos != value))
				{
					this._idcursos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcarrera", DbType="Int NOT NULL")]
		public int idcarrera
		{
			get
			{
				return this._idcarrera;
			}
			set
			{
				if ((this._idcarrera != value))
				{
					this._idcarrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semestre", DbType="Int NOT NULL")]
		public int semestre
		{
			get
			{
				return this._semestre;
			}
			set
			{
				if ((this._semestre != value))
				{
					this._semestre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obs", DbType="VarChar(45)")]
		public string obs
		{
			get
			{
				return this._obs;
			}
			set
			{
				if ((this._obs != value))
				{
					this._obs = value;
				}
			}
		}
	}
	
	public partial class SP_NUEVA_MATRICULAResult
	{
		
		private System.Nullable<decimal> _ideMat;
		
		public SP_NUEVA_MATRICULAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ideMat", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> ideMat
		{
			get
			{
				return this._ideMat;
			}
			set
			{
				if ((this._ideMat != value))
				{
					this._ideMat = value;
				}
			}
		}
	}
	
	public partial class SP_LISTA_MATRICULAResult
	{
		
		private int _idmatricula;
		
		private string _dni;
		
		private string _nombres;
		
		private System.Nullable<int> _semestre;
		
		private int _idcursos;
		
		private string _nombre;
		
		private System.Nullable<System.DateTime> _fecha_matricula;
		
		private int _iddetalle_matricula;
		
		public SP_LISTA_MATRICULAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmatricula", DbType="Int NOT NULL")]
		public int idmatricula
		{
			get
			{
				return this._idmatricula;
			}
			set
			{
				if ((this._idmatricula != value))
				{
					this._idmatricula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this._dni = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(137) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semestre", DbType="Int")]
		public System.Nullable<int> semestre
		{
			get
			{
				return this._semestre;
			}
			set
			{
				if ((this._semestre != value))
				{
					this._semestre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcursos", DbType="Int NOT NULL")]
		public int idcursos
		{
			get
			{
				return this._idcursos;
			}
			set
			{
				if ((this._idcursos != value))
				{
					this._idcursos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_matricula", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_matricula
		{
			get
			{
				return this._fecha_matricula;
			}
			set
			{
				if ((this._fecha_matricula != value))
				{
					this._fecha_matricula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddetalle_matricula", DbType="Int NOT NULL")]
		public int iddetalle_matricula
		{
			get
			{
				return this._iddetalle_matricula;
			}
			set
			{
				if ((this._iddetalle_matricula != value))
				{
					this._iddetalle_matricula = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
